---
# tasks file for neovim-bootstrap
- include_tasks: install.yml
- name: Create config directory
  file:
    path: '{{ neovim_config_dir }}'
    state: directory
    recurse: yes
- name: Put config endpoint
  template:
    src: init.vim.j2
    dest: '{{ neovim_config_dir }}/init.vim'
- name: Create lang-config directory
  file:
    path: '{{ neovim_config_dir }}/langs'
    state: directory
    recurse: yes
  when: neovim_langs
- name: Copy langs bundle file
  copy:
    src: '{{ item }}/bundle.vim'
    dest: '{{ neovim_config_dir }}/langs/{{ item }}-bundle.vim'
  when: neovim_langs
  with_items: '{{ neovim_langs }}'
- name: Copy langs config file
  copy:
    src: '{{ item }}/config.vim'
    dest: '{{ neovim_config_dir }}/langs/{{ item }}-config.vim'
  when: neovim_langs
  with_items: '{{ neovim_langs }}'
