---
# tasks file for neovim-bootstrap
- include_tasks: install.yml
- name: Create config directory
  file:
    path: '{{ neovim_config_dir }}'
    state: directory
    recurse: yes
- name: Put config endpoint
  template:
    src: init.vim.j2
    dest: '{{ neovim_config_dir }}/init.vim'
- include_tasks: langs.yml
  when: neovim_langs
