---
# tasks file for vim-bootstrap
- fail:
    msg: 'vim_config must be "vim" or "nvim"'
  when: vim_command not in ['vim', 'nvim']
- set_fact:
    vim_config_path: '{{ vim_config_dir }}/init.vim'
    vim_config_dir: '{{ ansible_env.HOME }}/.config/{{ vim_command }}'
  when: vim_command == 'nvim'
- set_fact:
    vim_config_path: '{{ ansible_env.HOME }}/.vim/vimrc'
    vim_config_dir: '{{ ansible_env.HOME }}/.vim'
  when: vim_command == 'vim'
- name: Create config directory
  file:
    path: '{{ vim_config_dir }}'
    state: directory
    recurse: yes
- name: Put config endpoint
  template:
    src: init.vim.j2
    dest: '{{ vim_config_path }}'
    backup: yes
- include_tasks: langs.yml
  when: vim_langs
