---
# tasks file for neovim-bootstrap
- name: Create config path
  file:
    path: '{{ neovim_config_path }}'
    state: directory
    recurse: yes
- name: Put config endpoint
  template:
    src: init.vim.j2
    dest: '{{ neovim_config_path }}/init.vim'
