---
# tasks file for neovim-bootstrap
- name: Create config path
  file:
    path: '{{ neovim_config_path }}'
    state: directory
    recurse: yes
- name: Copy file as init.vim
  copy:
    src: init.vim
    dest: '{{ neovim_config_path }}/init.vim'
